This is a testharness.js-based test.
FAIL Garbage collection ran during a writeValueWithResponse call that succeeds. Should not crash. promise_test: Unhandled rejection with value: object "ReferenceError: runGarbageCollection is not defined"
Harness: the test ran to completion.

