This is a testharness.js-based test.
FAIL cancel and close event properties are correct promise_test: Unhandled rejection with value: object "ReferenceError: CloseWatcher is not defined"
Harness: the test ran to completion.

