This is a testharness.js-based test.
FAIL Bad AuthenticatorSelectionCriteria: authenticatorSelection is empty array assert_unreached: Should have rejected: Expected bad parameters to fail Reached unreachable code
FAIL Bad AuthenticatorSelectionCriteria: authenticatorSelection is null assert_unreached: Should have rejected: Expected bad parameters to fail Reached unreachable code
PASS Bad AuthenticatorSelectionCriteria: authenticatorSelection is empty string
PASS Bad AuthenticatorSelectionCriteria: authenticatorSelection is string
PASS Bad AuthenticatorSelectionCriteria: authenticatorSelection attachment is empty string
PASS Bad AuthenticatorSelectionCriteria: authenticatorSelection attachment is empty object
PASS Bad AuthenticatorSelectionCriteria: authenticatorSelection attachment is null
PASS Bad AuthenticatorSelectionCriteria: authenticatorSelection attachment platform
PASS Bad AuthenticatorSelectionCriteria: authenticatorSelection residentKey true
FAIL Bad AuthenticatorSelectionCriteria: authenticatorSelection residentKey is string promise_rejects_js: Expected bad parameters to fail function "function() { throw e }" threw object "NotAllowedError: The operation either timed out or was not allowed. See: https://w3c.github.io/webauthn/#sec-assertion-privacy." ("NotAllowedError") expected instance of function "function TypeError() { [native code] }" ("TypeError")
PASS Bad AuthenticatorSelectionCriteria: authenticatorSelection userVerification empty string
PASS Bad AuthenticatorSelectionCriteria: authenticatorSelection userVerification empty object
PASS Bad AuthenticatorSelectionCriteria: authenticatorSelection userVerification bad value
PASS Bad AuthenticatorSelectionCriteria: authenticatorSelection userVerification null
PASS Bad AuthenticatorSelectionCriteria: authenticatorSelection userVerification required
PASS Clean up the test environment
Harness: the test ran to completion.

