This is a testharness.js-based test.
PASS Bad excludeCredentials: string
PASS Bad excludeCredentials: empty object
PASS excludeCredentials missing
PASS excludeCredentials empty array
FAIL exclude existing credential promise_rejects_dom: expected to fail on excluded credenetial function "function() { throw e }" threw object "InvalidStateError: The user attempted to register an authenticator that contains one of the credentials already registered with the relying party." that is not a DOMException NotAllowedError: property "code" is equal to 11, expected 0
PASS exclude random (non-existing) credential
PASS Clean up the test environment
Harness: the test ran to completion.

